### ISSUE TITLE
Remove DatabaseCleaner Gem (not needed in Rails 5)

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-api#82]
RSpec sometimes fails with "duplicate key value violates unique constraint "

`bundle exec rake` is not consistent.

Examples:
```
 1) V0::KitsController PUT /kits/:id does not update a kit with empty parameters access_token
     Failure/Error: let!(:kit) { create :kit }
     
     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "kits_pkey"
       DETAIL:  Key (id)=(3) already exists.
       : INSERT INTO "kits" ("name", "description", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
     # ./spec/requests/v0/kits_spec.rb:66:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::UniqueViolation:
     #   ERROR:  duplicate key value violates unique constraint "kits_pkey"
     #   DETAIL:  Key (id)=(3) already exists.
     #   ./spec/requests/v0/kits_spec.rb:66:in `block (3 levels) in <top (required)>'

  2) V0::KitsController GET /kits returns all the kits
     Failure/Error: expect(json.length).to eq(2)
     
       expected: 2
            got: 3
     
       (compared using ==)
     # ./spec/requests/v0/ki

```

Try running `bundle exec rake` multiple times, some tests sometimes pass.

**Comment by viktorsmari** [comment]
It is consistent for now but the DatabaseCleaner gem is not needed anymore according to:

https://stackoverflow.com/questions/49246124/is-databasecleaner-still-necessary-with-rails-system-specs
